### ISSUE TITLE
Transformation between two multivectors

### ISSUE THREAD

**Issue by Tannz0rz** [laffernandes/gatl#24]
In [this link at section 2.5](https://enki.ws/ganja.js/examples/coffeeshop.html#ydDtaGu0a&fullscreen) the transformation from `a` to `b` is expressed as: `a \rightarrow b = \sqrt { b * a^{-1} }`. How can I compute the square root of a multivector in GATL?

Also, is it appropriate for me to be using the "Issues" section for asking questions like this?

**Comment by Tannz0rz** [comment]
@laffernandes 

Enki (maker of Ganja.js) said this in the Bivector Discord:

```
I usually just go for sqrt(x) = (1 + x).Normalized (actually @tBuLi and me just submitted a paper with optimized implementations of normalisation , sqrt, etc .. for PGA, CGA, etc .. we prove that if you properly deal with normalize this formula is universally valid)
```

**Comment by laffernandes** [comment]
This is interesting. I was not aware of this trick. Please tell me later if it worked.

**Comment by Tannz0rz** [comment]
Can confirm the following does work:
```
template <typename T, typename FromExpression, typename ToExpression>
auto inverse_transform(clifford_expression<T, FromExpression> const &from_expression, clifford_expression<T, ToExpression> const &to_expression)
{
    return unit(static_cast<T>(1.0) + (to_expression * inv(from_expression)));
}
```
